//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int FeedBackId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> Face { get; set; }
        public string Opinion { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
